(function(){'use strict';
const APP_VERSION='v21';
const FORMATIONS=[
'4-2-1-3','4-4-1-1','4-2-3-1 Wide','4-3-3 Attack','4-1-2-1-2 Narrow','4-4-2','4-3-1-2','4-3-3 Holding','4-4-2 Holding','4-1-2-1-2 Wide','4-2-3-1','4-1-4-1','4-3-3 Defend','4-3-2-1','4-5-1 Flat','4-2-2-2','4-3-3','4-2-4','4-1-3-2','4-5-1 Attack','3-4-2-1','3-5-2','5-2-1-2','3-4-1-2','5-3-2','5-2-3','5-4-1','3-4-3','3-1-4-2'];
const FORM_ROWS={
'4-2-1-3':['GK','LB','CB','CB','RB','CM','CM','CAM','LW','ST','RW'],
'4-4-1-1':['GK','LB','CB','CB','RB','LM','CM','CM','RM','CF','ST'],
'4-2-3-1 Wide':['GK','LB','CB','CB','RB','CDM','CDM','LW','CAM','RW','ST'],
'4-3-3 Attack':['GK','LB','CB','CB','RB','CM','CM','CM','LW','ST','RW'],
'4-1-2-1-2 Narrow':['GK','LB','CB','CB','RB','CDM','CM','CM','CAM','ST','ST'],
'4-4-2':['GK','LB','CB','CB','RB','LM','CM','CM','RM','ST','ST'],
'4-3-1-2':['GK','LB','CB','CB','RB','CM','CM','CM','CAM','ST','ST'],
'4-3-3 Holding':['GK','LB','CB','CB','RB','CM','CDM','CM','LW','ST','RW'],
'4-4-2 Holding':['GK','LB','CB','CB','RB','LM','CDM','CDM','RM','ST','ST'],
'4-1-2-1-2 Wide':['GK','LB','CB','CB','RB','CDM','LM','RM','CAM','ST','ST'],
'4-2-3-1':['GK','LB','CB','CB','RB','CDM','CDM','LW','CAM','RW','ST'],
'4-1-4-1':['GK','LB','CB','CB','RB','CDM','LM','CM','CM','RM','ST'],
'4-3-3 Defend':['GK','LB','CB','CB','RB','CM','CM','CM','LW','ST','RW'],
'4-3-2-1':['GK','LB','CB','CB','RB','CM','CM','CM','CF','CF','ST'],
'4-5-1 Flat':['GK','LB','CB','CB','RB','LM','CM','CM','CM','RM','ST'],
'4-2-2-2':['GK','LB','CB','CB','RB','CDM','CDM','CAM','CAM','ST','ST'],
'4-3-3':['GK','LB','CB','CB','RB','CM','CM','CM','LW','ST','RW'],
'4-2-4':['GK','LB','CB','CB','RB','CM','CM','LW','ST','ST','RW'],
'4-1-3-2':['GK','LB','CB','CB','RB','CDM','LM','CAM','RM','ST','ST'],
'4-5-1 Attack':['GK','LB','CB','CB','RB','LM','CM','CAM','CM','RM','ST'],
'3-4-2-1':['GK','CB','CB','CB','LM','CM','CM','RM','CAM','CAM','ST'],
'3-5-2':['GK','CB','CB','CB','LM','CM','CDM','CM','RM','ST','ST'],
'5-2-1-2':['GK','LB','CB','CB','CB','RB','CM','CM','CAM','ST','ST'],
'3-4-1-2':['GK','CB','CB','CB','LM','CM','CM','RM','CAM','ST','ST'],
'5-3-2':['GK','LB','CB','CB','CB','RB','CM','CDM','CM','ST','ST'],
'5-2-3':['GK','LB','CB','CB','CB','RB','CM','CM','LW','ST','RW'],
'5-4-1':['GK','LB','CB','CB','CB','RB','LM','CM','CM','RM','ST'],
'3-4-3':['GK','CB','CB','CB','LM','CM','CM','RM','LW','ST','RW'],
'3-1-4-2':['GK','CB','CB','CB','CDM','LM','CM','CM','RM','ST','ST']};
const K={notes:'fc27_shared_notes',lineups:'fc27_shared_lineups',tactics:'fc27_shared_tactics',formation:'fc27_shared_formation'};
const state={own:null,opponent:null,sharedError:'',loadingShared:false,notes:jget(K.notes,''),lineups:jget(K.lineups,{}),tactics:jget(K.tactics,{lineHeight:55,width:50,build:55,pressure:45,tempo:50}),formation:jget(K.formation,'4-1-2-1-2 Narrow'),knowledge:null,knowledgeError:'',tab:'team',aiMode:'normal',matchFilter:''};
const el=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function jget(k,d){try{const x=localStorage.getItem(k);return x===null?d:JSON.parse(x)}catch{return d}}
function jset(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}}
function num(v,d=0){const n=Number(String(v??'').replace(',','.').replace('%',''));return Number.isFinite(n)?n:d}
function pct(a,b){const n=num(b);return n?100*num(a)/n:null}
function formatDate(v){if(v===null||v===undefined||v==='')return'';const n=Number(v);const d=Number.isFinite(n)?new Date(n<1e12?n*1000:n):new Date(v);if(Number.isNaN(d.getTime()))return String(v);return new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(d)}
function shortDate(v){if(!v)return'';const n=Number(v);const d=Number.isFinite(n)?new Date(n<1e12?n*1000:n):new Date(v);return Number.isNaN(d.getTime())?String(v):new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'2-digit',year:'numeric'}).format(d)}
function team(role){return role==='opponent'?state.opponent:state.own}
function roleLabel(role){return role==='opponent'?'Avversario':'La tua squadra'}
function competitionLabel(c){return c==='league'?'Campionato':c==='playoffs'?'Playoff':'Amichevoli'}
function resultLabel(r){return r==='W'?'VITTORIA':r==='L'?'SCONFITTA':'PAREGGIO'}
function resultClass(r){return r==='W'?'win':r==='L'?'loss':'draw'}
function dataReady(t){return Boolean(t?.ready)}
function complete(t){return Boolean(t?.complete)}
function fileCount(t){return ['players','league','playoffs','friendlies'].filter(k=>t?.fileStatus?.[k]?.present).length}
function statusLine(t){if(!t)return'Nessun dato condiviso';return `${fileCount(t)}/4 file · ${t.players?.length||0} giocatori · ${t.matches?.length||0} partite`}
function ownClubInMatch(t,m){return m?.clubs?.find(c=>String(c.id)===String(t?.club?.id))||m?.clubs?.[0]||null}
function oppClubInMatch(t,m){const own=ownClubInMatch(t,m);return m?.clubs?.find(c=>String(c.id)!==String(own?.id))||m?.clubs?.[1]||null}
function matchResult(t,m){const a=ownClubInMatch(t,m),b=oppClubInMatch(t,m);return num(a?.goals)>num(b?.goals)?'W':num(a?.goals)<num(b?.goals)?'L':'D'}
function department(p){const x=String(p||'').toLowerCase();if(/gk|goalkeeper|keeper/.test(x))return'GK';if(/lb|rb|cb|def|lwb|rwb/.test(x))return'DEF';if(/cm|cdm|lm|rm|cam|mid/.test(x))return'MID';if(/st|lw|rw|cf|att|forward/.test(x))return'ATT';return''}
function stat(v,label){return `<div class="stat"><strong>${esc(v)}</strong><span>${esc(label)}</span></div>`}
function showToast(t,err=false){const box=el('toast');if(!box)return;box.innerHTML=`<div class="message ${err?'err':'ok'}">${esc(t)}</div>`;box.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>box.classList.remove('show'),2800)}
function shell(kicker,title,content){return `<div class="kicker">${esc(kicker)}</div><h2 style="margin:6px 0 11px">${esc(title)}</h2>${content}`}
function empty(text){return `<div class="empty">${esc(text)}</div>`}
function setHeader(){const t=state.own;el('clubName').textContent=t?.club?.name||'SISAL FC 2021';el('clubId').textContent=t?.club?.id?`#${t.club.id}`:'—';el('status').textContent=statusLine(t)+(t?.updatedAt?` · aggiornato ${shortDate(t.updatedAt)}`:'');const ls=el('liveStatus');if(ls)ls.textContent=state.loadingShared?'Caricamento archivio centrale…':state.sharedError?'⚠ Archivio centrale non disponibile':t?`${complete(t)?'✓ Dataset completo':'⚠ Dataset parziale'} · condiviso per tutti gli utenti`:'Pronto · carica i file nella sezione I tuoi dati'}
function teamPage(){const t=state.own;if(!t||!dataReady(t))return shell('SQUADRA','Command Center',`<div class="hero"><div class="kicker">ARCHIVIO CENTRALE</div><h2>Dati non ancora caricati</h2><p>Carica i 4 file della tua squadra. Il sito li salva centralmente: gli altri compagni non dovranno ricaricarli.</p><button class="btn primary" data-goto="data">⚙️ Apri I tuoi dati</button></div>`);const o=t.overall||{},parts=t.byCompetition||{};return shell('SQUADRA',t.club?.name||'Sisal FC 2021',`<div class="hero"><div class="kicker">STAGIONE FC 27 · ARCHIVIO CONDIVISO</div><h2>${esc(t.club?.name||'Sisal FC 2021')}</h2><p>${complete(t)?'Giocatori + Campionato + Playoff + Amichevoli caricati.':'Dataset parziale: manca almeno un file.'}</p></div><div class="stats-grid">${stat(o.matches||0,'Partite')}${stat(o.wins||0,'Vittorie')}${stat(o.draws||0,'Pareggi')}${stat(o.losses||0,'Sconfitte')}${stat(o.goals||0,'Gol fatti')}${stat(o.against||0,'Gol subiti')}${stat(o.goalsPerMatch?.toFixed(2)||'0.00','Gol/partita')}${stat(o.concededPerMatch?.toFixed(2)||'0.00','Subiti/partita')}</div><div class="grid3" style="margin-top:10px">${['league','playoffs','friendlies'].map(k=>`<div class="card"><div class="section-title"><b>${competitionLabel(k)}</b><span class="tag">${parts[k]?.matches||0} PG</span></div><div class="muted">${parts[k]?.wins||0}V · ${parts[k]?.draws||0}P · ${parts[k]?.losses||0}S · ${parts[k]?.goals||0}-${parts[k]?.against||0}</div></div>`).join('')}</div><div class="grid2" style="margin-top:10px"><div class="card"><h3>Ultime 5</h3>${renderRecent(t,5)}</div><div class="card"><h3>Sezioni dati</h3>${dataStatusMini(t)}</div></div>`)}
function renderRecent(t,n=5,filter=''){const ms=(t?.matches||[]).filter(m=>!filter||m.competition===filter).slice(0,n);if(!ms.length)return empty('Nessuna partita disponibile.');return `<div class="rank-list">${ms.map(m=>{const op=oppClubInMatch(t,m),r=matchResult(t,m);return `<div class="rank-row"><div class="rank-no ${r==='W'?'f-win':r==='L'?'f-loss':'f-draw'}">${r}</div><div><b>${esc(op?.name||'Avversario')}</b><small>${competitionLabel(m.competition)} · ${shortDate(m.timestamp)}</small></div><div class="rank-val">${num(ownClubInMatch(t,m)?.goals)}-${num(op?.goals)}</div></div>`}).join('')}</div>`}
function dataStatusMini(t){const fs=t?.fileStatus||{};return `<div class="rank-list">${[['players','Giocatori'],['league','Campionato'],['playoffs','Playoff'],['friendlies','Amichevoli']].map(([k,l])=>`<div class="rank-row"><div class="rank-no">${fs[k]?.present?'✓':'—'}</div><div><b>${l}</b><small>${esc(fs[k]?.fileName||'File non caricato')}</small></div><div class="rank-val">${fs[k]?.present?'OK':'Manca'}</div></div>`).join('')}</div>`}
function playersPage(){const t=state.own;if(!dataReady(t))return shell('GIOCATORI','Statistiche individuali',empty('Carica i dati della tua squadra.'));const ps=t.players||[];return shell('GIOCATORI','Statistiche individuali',`<div class="toolbar"><div class="field"><label>Ricerca</label><input id="playerSearch" placeholder="Nome giocatore..."></div><div class="field"><label>Reparto</label><select id="playerDept"><option value="">Tutti</option><option value="GK">Portieri</option><option value="DEF">Difensori</option><option value="MID">Centrocampisti</option><option value="ATT">Attaccanti</option></select></div></div><div class="table-wrap"><table><thead><tr><th>Giocatore</th><th>PG</th><th>Gol</th><th>Assist</th><th>Voto</th><th>Passaggi</th><th>Contrasti</th><th>Tiri</th><th>Minuti</th></tr></thead><tbody id="playerRows">${ps.map((p,i)=>`<tr data-dep="${esc(department(p.position))}"><td><button class="player-link" data-player="${esc(p.id||i)}"><b class="name">${esc(p.name)}</b><small>${esc(p.position||'Posizione n/d')}</small></button></td><td>${p.games||0}</td><td>${p.goals||0}</td><td>${p.assists||0}</td><td class="rating">${p.rating==null?'—':num(p.rating).toFixed(2)}</td><td>${p.passAttempts?`${p.passesMade}/${p.passAttempts} (${pct(p.passesMade,p.passAttempts).toFixed(1)}%)`:'—'}</td><td>${p.tackleAttempts?`${p.tacklesMade}/${p.tackleAttempts} (${pct(p.tacklesMade,p.tackleAttempts).toFixed(1)}%)`:'—'}</td><td>${p.shots||0}</td><td>${p.secondsPlayed?Math.round(p.secondsPlayed/60):0}</td></tr>`).join('')}</tbody></table></div>`)}
function topPage(){const t=state.own;if(!dataReady(t))return shell('TOP 3','Classifiche',empty('Carica i dati della squadra.'));const p=t.players||[];const box=(title,arr,key,unit='')=>`<div class="card"><h3>${title}</h3><div class="rank-list">${arr.slice(0,3).map((x,i)=>`<div class="rank-row"><div class="rank-no">${i+1}</div><div><b>${esc(x.name)}</b><small>${esc(x.position||'')}</small></div><div class="rank-val">${num(x[key]).toFixed(key==='rating'?2:0)}${unit}</div></div>`).join('')}</div></div>`;const pass=[...p].filter(x=>x.passAttempts>0).map(x=>({...x,acc:pct(x.passesMade,x.passAttempts)})).sort((a,b)=>b.acc-a.acc).map(x=>({...x,passAccuracy:x.acc}));return shell('TOP 3','Classifiche individuali',`<div class="grid2">${box('⚽ Gol',[...p].sort((a,b)=>num(b.goals)-num(a.goals)),'goals')}${box('🎯 Assist',[...p].sort((a,b)=>num(b.assists)-num(a.assists)),'assists')}${box('⭐ Rating',[...p].filter(x=>num(x.games)>=3).sort((a,b)=>num(b.rating)-num(a.rating)),'rating')}${box('🎯 Pass accuracy',pass,'passAccuracy','%')}</div>`)}
function autoLineup(){const t=state.own;if(!dataReady(t)||!t.players?.length)return;const roles=FORM_ROWS[state.formation]||FORM_ROWS['4-1-2-1-2 Narrow'];const assigned={};const used=new Set();const fit=(p,role)=>{const d=department(p.position||p.pos||'');if(role==='GK')return d==='GK'?100:0;if(['LB','RB','CB'].includes(role))return d==='DEF'?100:0;if(['CDM','CM','LM','RM','CAM'].includes(role))return d==='MID'?100:0;return d==='ATT'?100:0};roles.forEach((role,i)=>{let best=null,score=-1;for(const p of t.players){if(used.has(String(p.id)))continue;const v=fit(p,role)*10+num(p.ovr)+num(p.rating)*2;if(v>score){score=v;best=p}}if(best){used.add(String(best.id));assigned[i]=best.id}});state.lineups[state.formation]=assigned;jset(K.lineups,state.lineups);render()}
function pitchPage(){const t=state.own;if(!dataReady(t))return shell('CAMPO','Formazione',empty('Carica prima i giocatori.'));const roles=FORM_ROWS[state.formation]||FORM_ROWS['4-1-2-1-2 Narrow'],assigned=state.lineups[state.formation]||{};return shell('CAMPO','Formazione e tattiche',`<div class="pitch-layout"><div class="pitch-card"><div class="pitch"><div class="box-line top"></div><div class="box-line bottom"></div>${roles.map((role,i)=>{const p=t.players.find(x=>String(x.id)===String(assigned[i]));const x=50+(i%3-1)*28,y=87-(i/(roles.length-1||1))*74;return `<div class="dot" style="left:${x}%;top:${y}%"><span>${esc(p?.name||role)}</span></div>`}).join('')}</div></div><div class="card"><div class="field"><label>Modulo</label><select id="formation">${Object.keys(FORM_ROWS).map(f=>`<option value="${esc(f)}" ${f===state.formation?'selected':''}>${esc(f)}</option>`).join('')}</select></div><div class="two-actions" style="margin-top:9px"><button class="btn primary" id="autoLineup">⚡ Auto-formazione</button><button class="btn" id="clearLineup">Pulisci</button></div>${roles.map((role,i)=>`<div class="field" style="margin-top:7px"><label>${role}</label><select data-slot="${i}"><option value="">—</option>${t.players.map(p=>`<option value="${esc(p.id)}" ${String(assigned[i])===String(p.id)?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div>`).join('')}</div></div>`)}
function matchesPage(){const t=state.own;if(!dataReady(t))return shell('PARTITE','Archivio',empty('Carica i dati della squadra.'));const ms=(t.matches||[]).filter(m=>!state.matchFilter||m.competition===state.matchFilter);return shell('PARTITE','Archivio completo',`<div class="toolbar"><div class="field"><label>Competizione</label><select id="matchFilter"><option value="">Tutte</option><option value="league" ${state.matchFilter==='league'?'selected':''}>Campionato</option><option value="playoffs" ${state.matchFilter==='playoffs'?'selected':''}>Playoff</option><option value="friendlies" ${state.matchFilter==='friendlies'?'selected':''}>Amichevoli</option></select></div></div><div class="muted">${ms.length} partite.</div><div class="match-grid" style="margin-top:9px">${ms.map(m=>{const own=ownClubInMatch(t,m),op=oppClubInMatch(t,m),r=matchResult(t,m),ps=(m.players||[]).filter(p=>!t.club?.id||String(p.clubId)===String(t.club.id));return `<article class="match-card"><div class="match-top"><span>${competitionLabel(m.competition)} · ${formatDate(m.timestamp)}</span><span>#${esc(m.id)}</span></div><div class="score-grid"><div class="team-side"><b>${esc(own?.name||t.club.name)}</b></div><strong class="score-big">${num(own?.goals)}-${num(op?.goals)}</strong><div class="team-side"><b>${esc(op?.name||'Avversario')}</b></div></div><span class="result-pill ${resultClass(r)}">${resultLabel(r)}</span>${ps.length?`<button class="btn" data-match="${esc(m.id)}" style="margin-top:10px;width:100%">Statistiche partita</button><div class="match-detail hidden" id="det_${esc(m.id)}"><div class="table-wrap"><table><thead><tr><th>Giocatore</th><th>Gol</th><th>Assist</th><th>Voto</th><th>Pass</th><th>Tackle</th></tr></thead><tbody>${ps.map(p=>`<tr><td>${esc(p.name)}</td><td>${p.goals||0}</td><td>${p.assists||0}</td><td>${p.rating==null?'—':num(p.rating).toFixed(2)}</td><td>${p.passAttempts?`${p.passesMade}/${p.passAttempts}`:'—'}</td><td>${p.tackleAttempts?`${p.tacklesMade}/${p.tackleAttempts}`:'—'}</td></tr>`).join('')}</tbody></table></div></div>`:''}</article>`}).join('')}</div>`)}
function funPage(){const t=state.own;if(!dataReady(t))return shell('FUN','Fun · record',empty('Carica i dati della squadra.'));const rec=t.fun?.records||[],flags=t.fun?.redFlags||[],form=t.fun?.form||[];return shell('FUN','Fun · record della stagione',`<div class="hero"><div class="kicker">ISPIRATA ALLE FUNZIONI PUBBLICHE DEI TRACKER</div><h2>Record, forma e red flags</h2><p>Tutto è calcolato automaticamente dai file di Giocatori, Campionato, Playoff e Amichevoli. Nessun dato esterno.</p></div><div class="card"><h3>Forma ultime 10</h3><div class="form">${form.length?form.map((x,i)=>`<b class="f-${x.toLowerCase()}" title="${i+1}">${x}</b>`).join(''):empty('Nessuna partita disponibile.')}</div></div><div class="grid2" style="margin-top:10px"><div class="card"><h3>🏆 Premi e record</h3><div class="rank-list">${(rec.length?rec:[{title:'Nessun record',value:'—',subtitle:'Dati insufficienti'}]).map(x=>`<div class="rank-row"><div class="rank-no">★</div><div><b>${esc(x.title)}</b><small>${esc(x.subtitle||'')}</small></div><div class="rank-val">${esc(x.value)}</div></div>`).join('')}</div></div><div class="card"><h3>🚩 Red flags</h3><div class="rank-list">${(flags.length?flags:[{title:'Nessuna red flag forte',value:'—',subtitle:'Non emerge un problema numerico evidente.'}]).map(x=>`<div class="rank-row"><div class="rank-no">!</div><div><b>${esc(x.title)}</b><small>${esc(x.subtitle||'')}</small></div><div class="rank-val">${esc(x.value)}</div></div>`).join('')}</div></div></div>`)}
function opponentPage(){const t=state.opponent;if(!dataReady(t))return shell('AVVERSARIO','Scouting',`<div class="hero"><div class="kicker">DATASET CONDIVISO</div><h2>Avversario non caricato</h2><p>Carica i 4 file dell’avversario dalla sezione I tuoi dati. Una volta caricati, tutti vedranno lo stesso scouting.</p><button class="btn primary" data-goto="data">⚙️ Apri I tuoi dati</button></div>`);const o=t.overall||{};return shell('AVVERSARIO',t.club?.name||'Avversario',`<div class="stats-grid">${stat(o.matches||0,'Partite')}${stat(o.wins||0,'Vittorie')}${stat(o.draws||0,'Pareggi')}${stat(o.losses||0,'Sconfitte')}${stat(o.goals||0,'Gol')}${stat(o.against||0,'Subiti')}</div><div class="grid2" style="margin-top:10px"><div class="card"><h3>Ultime 10</h3>${renderRecent(t,10)}</div><div class="card"><h3>Scouting IA</h3><p class="muted">Premi il pulsante per analizzare l’avversario confrontandolo con i dati della tua squadra.</p><button class="btn primary" id="askOpponentAI">✦ Analizza avversario</button><div class="ai-result" id="opAIResult" style="margin-top:9px"></div></div></div>`)}
function aiPage(){const opponentMode=state.aiMode==='opponent';return shell('IA','Assistente tattico',`<div class="grid2"><div class="card"><div class="kicker">GEMINI 3.5 FLASH-LITE</div><h3>${opponentMode?'Scouting avversario':'Analisi della squadra'}</h3><div class="two-actions" style="margin-bottom:9px"><button class="btn ${!opponentMode?'primary':''}" id="aiTeamMode">Squadra</button><button class="btn ${opponentMode?'primary':''}" id="aiOppMode">Avversario</button></div><textarea id="aiQ" placeholder="Esempio: analizza tutte le partite e indicami i problemi principali da correggere."></textarea><div class="two-actions" style="margin-top:9px"><button class="btn primary" id="askAI">✦ Analizza</button><button class="btn" data-q="Analizza tutte le partite e dimmi i nostri punti deboli principali.">Punti deboli</button><button class="btn" data-q="Quali giocatori rendono meglio considerando tutti i dati?"><span>Giocatori</span></button><button class="btn" data-q="Confronta la nostra squadra con l’avversario.">Confronto</button></div></div><div class="card"><h3>Risposta</h3><div class="ai-result" id="aiResult">L’IA legge direttamente il dataset centrale.</div></div></div><div class="notice" style="margin-top:10px">Il backend rilegge sempre i dati condivisi dal server. Il browser non può alterare i numeri passati all’IA.</div>`)}
function dataPage(){return shell('DATI','Archivio centrale',`<div class="hero"><div class="kicker">UNA VOLTA SOLA PER TUTTA LA SQUADRA</div><h2>Carica i file della stagione</h2><p>Il sito salva i dati centralmente. Quando un compagno apre il sito, vede automaticamente gli stessi file già caricati.</p><div class="tag">4 file per squadra</div></div><div class="grid2"><div>${teamDataCard('own','La tua squadra')}</div><div>${teamDataCard('opponent','Avversario')}</div></div><div class="card" style="margin-top:10px"><h3>Formato</h3><p class="muted">Puoi usare .json oppure .txt. Il contenuto deve essere il JSON originale. Le quattro categorie sono obbligatorie per considerare il dataset completo.</p></div><div class="card" style="margin-top:10px"><h3>Note squadra</h3><textarea id="notes" placeholder="Note tattiche, ruoli, cose da provare...">${esc(state.notes)}</textarea><button class="btn" id="saveNotes" style="margin-top:8px">Salva note</button></div>`)}
function teamDataCard(role,title){const t=team(role),fs=t?.fileStatus||{},cats=[['players','Giocatori'],['league','Partite di campionato'],['playoffs','Playoff'],['friendlies','Amichevoli']];return `<div class="card sync-card"><div class="section-title"><b>${title}</b><span class="tag ${complete(t)?'live':'warn'}">${fileCount(t)}/4</span></div><div class="muted" style="margin-bottom:9px">${esc(t?.club?.name||'Nessun dato caricato')}</div><div class="file-slots">${cats.map(([cat,label])=>{const f=fs[cat];return `<div class="file-slot"><div><b>${label}</b><small>${f?.present?esc(f.fileName):'Nessun file caricato'}</small></div><button class="btn" data-upload-role="${role}" data-upload-cat="${cat}">${f?.present?'Aggiorna':'Carica'}</button><input class="hidden" id="file_${role}_${cat}" type="file" accept=".json,.txt,application/json,text/plain"></div>`}).join('')}</div><div class="two-actions" style="margin-top:10px"><button class="btn primary" data-upload-all="${role}">📦 Carica 4 file insieme</button><button class="btn danger" data-delete-role="${role}">🗑️ Cancella tutti i dati</button></div><div class="messages" id="${role}Messages"></div></div>`}
function updateAICoverage(){}
async function loadSharedData(){state.loadingShared=true;render();try{const r=await fetch('/api/club-data',{cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`Errore HTTP ${r.status}`);state.own=d.teams?.own||null;state.opponent=d.teams?.opponent||null;state.sharedError=''}catch(e){state.own=null;state.opponent=null;state.sharedError=e.message||'Archivio non disponibile'}finally{state.loadingShared=false;render()}}
async function uploadOne(role,cat,file){if(!file)return;const box=el(`${role}Messages`);if(box)box.innerHTML=`<div class="message">⏳ Lettura e salvataggio di ${esc(file.name)}…</div>`;const form=new FormData();form.set('role',role);form.set('category',cat);form.set('file',file);try{const r=await fetch('/api/club-data',{method:'POST',body:form});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`Errore HTTP ${r.status}`);showToast(`✓ ${file.name} salvato nel dataset centrale`);await loadSharedData()}catch(e){if(box)box.innerHTML=`<div class="message err">✕ ${esc(e.message)}</div>`;showToast(e.message||'Caricamento fallito',true)}}
async function uploadAll(role,files){const list=[...files];if(list.length!==4){showToast('Seleziona esattamente 4 file.',true);return}const rules=[['players',/player|giocator|member|roster/i],['league',/league|campionat/i],['playoffs',/playoff|play-off/i],['friendlies',/friendly|amichevol/i]];const assigned=new Map();for(const f of list){for(const [cat,re] of rules){if(re.test(f.name)&&!assigned.has(cat)){assigned.set(cat,f);break}}}if(assigned.size!==4){showToast('I nomi dei 4 file non permettono di capire la categoria. Usa i quattro pulsanti singoli: Giocatori, Campionato, Playoff e Amichevoli.',true);return}for(const [cat,f] of assigned)await uploadOne(role,cat,f)}
async function deleteRole(role){if(!confirm(`Cancellare tutti i 4 file della ${role==='own'?'tua squadra':'squadra avversaria'} dal server?`))return;try{const r=await fetch(`/api/club-data?role=${encodeURIComponent(role)}`,{method:'DELETE'});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`Errore HTTP ${r.status}`);showToast('✓ Dati cancellati dal server');await loadSharedData()}catch(e){showToast(e.message||'Cancellazione fallita',true)}}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render();window.scrollTo({top:0,behavior:'smooth'})});document.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.goto;render()});const save=el('saveNotes'),notes=el('notes');if(save&&notes)save.onclick=()=>{state.notes=notes.value;jset(K.notes,state.notes);showToast('✓ Note salvate')};const formation=el('formation');if(formation)formation.onchange=()=>{state.formation=formation.value;jset(K.formation,state.formation);render()};const auto=el('autoLineup');if(auto)auto.onclick=autoLineup;const clear=el('clearLineup');if(clear)clear.onclick=()=>{state.lineups[state.formation]={};jset(K.lineups,state.lineups);render()};document.querySelectorAll('[data-slot]').forEach(s=>s.onchange=()=>{state.lineups[state.formation]||={};state.lineups[state.formation][s.dataset.slot]=s.value;jset(K.lineups,state.lineups);render()});document.querySelectorAll('[data-player]').forEach(b=>b.onclick=()=>playerModal(b.dataset.player));document.querySelectorAll('[data-match]').forEach(b=>b.onclick=()=>{const x=el('det_'+b.dataset.match);if(x)x.classList.toggle('hidden')});document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{const q=el('aiQ');if(q)q.value=b.dataset.q});const ask=el('askAI');if(ask)ask.onclick=()=>callAI(el('aiQ').value,state.aiMode);const aiTeam=el('aiTeamMode');if(aiTeam)aiTeam.onclick=()=>{state.aiMode='normal';render()};const aiOpp=el('aiOppMode');if(aiOpp)aiOpp.onclick=()=>{state.aiMode='opponent';render()};const askOp=el('askOpponentAI');if(askOp)askOp.onclick=()=>callAI('Analizza questo avversario e confrontalo con la nostra squadra: punti forti, punti deboli, giocatori chiave, cosa limitare e come impostare la gara.', 'opponent');const ps=el('playerSearch'),pd=el('playerDept');if(ps&&pd){const update=()=>{const q=ps.value.toLowerCase(),d=pd.value;document.querySelectorAll('#playerRows tr').forEach(r=>{const name=r.querySelector('.name')?.textContent.toLowerCase()||'',dep=r.dataset.dep||'';r.style.display=(!q||name.includes(q))&&(!d||dep===d)?'':'none'})};ps.oninput=update;pd.onchange=update}const mf=el('matchFilter');if(mf)mf.onchange=()=>{state.matchFilter=mf.value;render()};document.querySelectorAll('[data-upload-role]').forEach(b=>b.onclick=()=>el(`file_${b.dataset.uploadRole}_${b.dataset.uploadCat}`)?.click());document.querySelectorAll('input[id^="file_"]').forEach(i=>i.onchange=()=>{const p=i.id.split('_');uploadOne(p[1],p[2],i.files?.[0]);i.value=''});document.querySelectorAll('[data-upload-all]').forEach(b=>b.onclick=()=>{const i=document.createElement('input');i.type='file';i.multiple=true;i.accept='.json,.txt,application/json,text/plain';i.onchange=()=>uploadAll(b.dataset.uploadAll,i.files||[]);i.click()});document.querySelectorAll('[data-delete-role]').forEach(b=>b.onclick=()=>deleteRole(b.dataset.deleteRole));}
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&el('modalRoot'))el('modalRoot').innerHTML=''});
async function loadKnowledge(){try{const r=await fetch('./knowledge/fc27-knowledge.json',{cache:'no-store'});if(r.ok)state.knowledge=await r.json()}catch{state.knowledgeError='Knowledge non disponibile'}}
function render(){setHeader();document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));const t=state.tab;el('content').innerHTML=t==='team'?teamPage():t==='players'?playersPage():t==='top'?topPage():t==='pitch'?pitchPage():t==='matches'?matchesPage():t==='fun'?funPage():t==='opponent'?opponentPage():t==='ai'?aiPage():dataPage();bind()}
function boot(){render();loadSharedData();loadKnowledge()}
boot();
if('serviceWorker' in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js?v=21').catch(()=>{});
})();
