import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=process.cwd();
const must=['index.html','index-inline.js','api/assistente.js','api/club-data.js','api/health.js','lib/data-pipeline.js','lib/shared-store.js','package.json','sw.js','manifest.webmanifest','.env.example'];
for(const f of must)await fs.access(path.join(root,f));
const pkg=JSON.parse(await fs.readFile(path.join(root,'package.json'),'utf8'));
assert.equal(pkg.engines.node,'24.x');assert.ok(pkg.dependencies['@vercel/blob']);assert.equal(pkg.version,'9.0.0');assert.equal(Boolean(pkg.dependencies.puppeteer),false);assert.equal(Boolean(pkg.dependencies['puppeteer-core']),false);
const html=await fs.readFile(path.join(root,'index.html'),'utf8');assert.match(html,/index-inline\.js\?v=21/);assert.doesNotMatch(html,/syncOwn|syncOpp|scrape-stats/);
const js=await fs.readFile(path.join(root,'index-inline.js'),'utf8');for(const text of ['Carica 4 file insieme','Giocatori','Partite di campionato','Playoff','Amichevoli','Cancella tutti i dati','/api/club-data','UNA VOLTA SOLA PER TUTTA LA SQUADRA'])assert.match(js,new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.doesNotMatch(js,/scrape-stats|proclubs\.ea\.com|GROQ|puppeteer|DATA_ADMIN_PIN|x-admin-pin|PIN amministratore|sessionStorage\.getItem\('fc27_data_admin_pin'\)/i);
const api=await fs.readFile(path.join(root,'api/club-data.js'),'utf8');assert.match(api,/readAllFiles/);assert.doesNotMatch(api,/proclubs\.ea\.com|puppeteer|GROQ|DATA_ADMIN_PIN|x-admin-pin|authorize\(/i);
console.log('verify-project: OK');
