import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=process.cwd();
const must=['index.html','index-inline.js','api/assistente.js','api/club-data.js','api/health.js','lib/data-pipeline.js','lib/shared-store.js','lib/file-ai-recognizer.js','lib/proclubs-schema.js','lib/tracker-import.js','package.json','sw.js','manifest.webmanifest','env.example'];
for(const f of must)await fs.access(path.join(root,f));
const pkg=JSON.parse(await fs.readFile(path.join(root,'package.json'),'utf8'));
assert.equal(pkg.version,'32.0.0');
assert.equal(pkg.engines.node,'24.x');
assert.ok(pkg.dependencies['@vercel/blob']);
assert.equal(Boolean(pkg.dependencies.puppeteer),false);
assert.equal(Boolean(pkg.dependencies['puppeteer-core']),false);
const html=await fs.readFile(path.join(root,'index.html'),'utf8');
assert.match(html,/index-inline\.js\?v=32\.0/);
assert.doesNotMatch(html,/syncOwn|syncOpp|scrape-stats/);
const js=await fs.readFile(path.join(root,'index-inline.js'),'utf8');
for(const text of ['Dati totali','Stagione corrente','Overall Stats','Giocatori','Carriera giocatori','Campionato','Playoff','Amichevoli','Playoff Achievements','OVR','Profilo Pro','Informazioni club','/api/club-data','DATA_FILES']) assert.match(js,new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));
assert.match(js,/APP_VERSION='v32\.0'/); assert.match(js,/data-pitch-slot/); assert.match(js,/kitPreview/); assert.match(html,/assets\/sisal-header\.png/);
assert.doesNotMatch(js,/proclubs\.ea\.com|GROQ|puppeteer|DATA_ADMIN_PIN|x-admin-pin|sessionStorage\.getItem\('fc27_data_admin_pin'\)/i);
assert.doesNotMatch(js,/Ultime 10|U10|Formazione \+ ruoli consigliati dall’IA|data-edit-totals|data-save-and-import-tracker|trackerUrl_|Storico codici recenti dell'export|Finish gruppo 1/i);
const api=await fs.readFile(path.join(root,'api/club-data.js'),'utf8');
assert.match(api,/readAllFiles/); assert.match(api,/recognizeDataFile/); assert.match(api,/extractHistoricalTotals/);
const assistant=await fs.readFile(path.join(root,'api/assistente.js'),'utf8');
assert.match(assistant,/teamProfile/); assert.match(assistant,/sourceFields/); assert.match(assistant,/career: p\.career/); assert.match(assistant,/proHeight/);
console.log('verify-project: OK');
