import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=process.cwd();
const must=['index.html','index-inline.js','api/assistente.js','api/club-data.js','api/health.js','lib/data-pipeline.js','lib/shared-store.js','lib/file-ai-recognizer.js','lib/proclubs-schema.js','lib/tracker-import.js','package.json','scripts/test-formation.mjs','scripts/test-v321-metrics.mjs','scripts/test-v3212-profiles.mjs','scripts/test-v3213-profile-ai.mjs','scripts/test-branding-asset.mjs','sw.js','manifest.webmanifest','env.example'];
for(const f of must)await fs.access(path.join(root,f));
const pkg=JSON.parse(await fs.readFile(path.join(root,'package.json'),'utf8'));
assert.equal(pkg.version,'32.1.3');
assert.equal(pkg.engines.node,'24.x');
assert.ok(pkg.dependencies['@vercel/blob']);
assert.equal(Boolean(pkg.dependencies.puppeteer),false);
assert.equal(Boolean(pkg.dependencies['puppeteer-core']),false);
const html=await fs.readFile(path.join(root,'index.html'),'utf8');
assert.match(html,/index-inline\.js\?v=32\.1\.3/);
assert.doesNotMatch(html,/syncOwn|syncOpp|scrape-stats/);
const js=await fs.readFile(path.join(root,'index-inline.js'),'utf8');
for(const text of ['Dati totali','Stagione corrente','Overall Stats','Giocatori','Carriera giocatori','Campionato','Playoff','Amichevoli','Playoff Achievements','OVR','Profilo Pro','Informazioni club','/api/club-data','DATA_FILES']) assert.match(js,new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));
assert.match(js,/APP_VERSION='v32.1.3'/);
assert.match(html,/assets\/sisal-branding\.png\?v=32\.1\.3-logo/);
assert.match(js,/function profileScopeRows\(scope\)/); assert.match(js,/Clean sheet/); assert.match(js,/Partite playoff/); assert.doesNotMatch(js,/Percentuale vittorie|Percentuale pareggi|Percentuale sconfitte|Percentuale imbattibilità|Percentuale clean sheet|Gol \/ partita|Gol subiti \/ partita|Punti \/ partita|Partite playoff %/);
assert.doesNotMatch(js,/proclubs\.ea\.com|GROQ|puppeteer|DATA_ADMIN_PIN|x-admin-pin|sessionStorage\.getItem\('fc27_data_admin_pin'\)/i);
assert.doesNotMatch(js,/Ultime 10|U10|Formazione \+ ruoli consigliati dall’IA|data-edit-totals|data-save-and-import-tracker|trackerUrl_/i);
assert.doesNotMatch(js,/Storico codici recenti dell'export|lastMatch code|lastOpponent ID|Kit casa|Kit trasferta|Terzo kit|Kit portiere|kitPreview|kitId|customKitId|customAwayKitId|customThirdKitId|customKeeperKitId|kitColor1|kitAColor1|kitThrdColor1/i);
assert.match(js,/data-pitch-slot/);
assert.match(await fs.readFile(path.join(root,'api/club-data.js'),'utf8'),/recentCodes/);
const api=await fs.readFile(path.join(root,'api/club-data.js'),'utf8');
assert.match(api,/readAllFiles/); assert.match(api,/recognizeDataFile/); assert.match(api,/extractHistoricalTotals/);
const assistant=await fs.readFile(path.join(root,'api/assistente.js'),'utf8');
assert.match(assistant,/teamProfile/); assert.match(assistant,/sourceFields/); assert.match(assistant,/career: p\.career/); assert.match(assistant,/proHeight/);
assert.match(await fs.readFile(path.join(root,'lib/file-ai-recognizer.js'),'utf8'),/parseProfileFields|profileFields/);
assert.match(api,/repairMissingClubProfiles|profileFields/);
console.log('verify-project: OK');
